package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private int codigoA;
     private String descricao;
     private Integer peso;
     private Set realizas = new HashSet(0);

    public Avaliacao() {
    }

	
    public Avaliacao(int codigoA) {
        this.codigoA = codigoA;
    }
    public Avaliacao(int codigoA, String descricao, Integer peso, Set realizas) {
       this.codigoA = codigoA;
       this.descricao = descricao;
       this.peso = peso;
       this.realizas = realizas;
    }
   
    public int getCodigoA() {
        return this.codigoA;
    }
    
    public void setCodigoA(int codigoA) {
        this.codigoA = codigoA;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }

    @Override
    public String toString() {
        return "Avaliacao{" + "codigoA=" + codigoA + ", descricao=" + descricao + ", peso=" + peso + ", realizas=" + realizas + '}';
    }




}


