package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int codCurso;
     private String nome;
     private Set disciplinas = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int codCurso) {
        this.codCurso = codCurso;
    }
    public Curso(int codCurso, String nome, Set disciplinas) {
       this.codCurso = codCurso;
       this.nome = nome;
       this.disciplinas = disciplinas;
    }
   
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }

    @Override
    public String toString() {
        return "Curso{" + "codCurso=" + codCurso + ", nome=" + nome + ", disciplinas=" + disciplinas + '}';
    }




}


