package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private int codD;
     private Curso curso;
     private String nome;
     private Integer credito;
     private Integer ch;
     private Set estudantes = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(int codD) {
        this.codD = codD;
    }
    public Disciplina(int codD, Curso curso, String nome, Integer credito, Integer ch, Set estudantes) {
       this.codD = codD;
       this.curso = curso;
       this.nome = nome;
       this.credito = credito;
       this.ch = ch;
       this.estudantes = estudantes;
    }
   
    public int getCodD() {
        return this.codD;
    }
    
    public void setCodD(int codD) {
        this.codD = codD;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }
    public Integer getCh() {
        return this.ch;
    }
    
    public void setCh(Integer ch) {
        this.ch = ch;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }

    @Override
    public String toString() {
        return "Disciplina{" + "codD=" + codD + ", curso=" + curso + ", nome=" + nome + ", credito=" + credito + ", ch=" + ch + ", estudantes=" + estudantes + '}';
    }




}


