package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private int nrmatricula;
     private String nome;
     private String apelido;
     private String endereco;
     private String contacto;
     private Byte isDeleted;
     private Set realizas = new HashSet(0);
     private Set disciplinas = new HashSet(0);

    public Estudante() {
    }

	
    public Estudante(int nrmatricula) {
        this.nrmatricula = nrmatricula;
    }
    public Estudante(int nrmatricula, String nome, String apelido, String endereco, String contacto, Byte isDeleted, Set realizas, Set disciplinas) {
       this.nrmatricula = nrmatricula;
       this.nome = nome;
       this.apelido = apelido;
       this.endereco = endereco;
       this.contacto = contacto;
       this.isDeleted = isDeleted;
       this.realizas = realizas;
       this.disciplinas = disciplinas;
    }
   
    public int getNrmatricula() {
        return this.nrmatricula;
    }
    
    public void setNrmatricula(int nrmatricula) {
        this.nrmatricula = nrmatricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }

    @Override
    public String toString() {
        return "Estudante{" + "nrmatricula=" + nrmatricula + ", nome=" + nome + ", apelido=" + apelido + ", endereco=" + endereco + ", contacto=" + contacto + ", isDeleted=" + isDeleted + ", realizas=" + realizas + ", disciplinas=" + disciplinas + '}';
    }




}


