package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1



/**
 * Realiza generated by hbm2java
 */
public class Realiza  implements java.io.Serializable {


     private RealizaId id;
     private Avaliacao avaliacao;
     private Estudante estudante;
     private Integer nota;

    public Realiza() {
    }

	
    public Realiza(RealizaId id, Avaliacao avaliacao, Estudante estudante) {
        this.id = id;
        this.avaliacao = avaliacao;
        this.estudante = estudante;
    }
    public Realiza(RealizaId id, Avaliacao avaliacao, Estudante estudante, Integer nota) {
       this.id = id;
       this.avaliacao = avaliacao;
       this.estudante = estudante;
       this.nota = nota;
    }
   
    public RealizaId getId() {
        return this.id;
    }
    
    public void setId(RealizaId id) {
        this.id = id;
    }
    public Avaliacao getAvaliacao() {
        return this.avaliacao;
    }
    
    public void setAvaliacao(Avaliacao avaliacao) {
        this.avaliacao = avaliacao;
    }
    public Estudante getEstudante() {
        return this.estudante;
    }
    
    public void setEstudante(Estudante estudante) {
        this.estudante = estudante;
    }
    public Integer getNota() {
        return this.nota;
    }
    
    public void setNota(Integer nota) {
        this.nota = nota;
    }

    @Override
    public String toString() {
        return "Realiza{" + "id=" + id + ", avaliacao=" + avaliacao + ", estudante=" + estudante + ", nota=" + nota + '}';
    }




}


