package model;
// Generated Jun 5, 2024 10:55:49 PM by Hibernate Tools 4.3.1



/**
 * RealizaId generated by hbm2java
 */
public class RealizaId  implements java.io.Serializable {


     private int nrmatricula;
     private int codigoA;

    public RealizaId() {
    }

    public RealizaId(int nrmatricula, int codigoA) {
       this.nrmatricula = nrmatricula;
       this.codigoA = codigoA;
    }
   
    public int getNrmatricula() {
        return this.nrmatricula;
    }
    
    public void setNrmatricula(int nrmatricula) {
        this.nrmatricula = nrmatricula;
    }
    public int getCodigoA() {
        return this.codigoA;
    }
    
    public void setCodigoA(int codigoA) {
        this.codigoA = codigoA;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RealizaId) ) return false;
		 RealizaId castOther = ( RealizaId ) other; 
         
		 return (this.getNrmatricula()==castOther.getNrmatricula())
 && (this.getCodigoA()==castOther.getCodigoA());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNrmatricula();
         result = 37 * result + this.getCodigoA();
         return result;
   }   

    @Override
    public String toString() {
        return "RealizaId{" + "nrmatricula=" + nrmatricula + ", codigoA=" + codigoA + '}';
    }


}


